# Fichier de configuration du site Ã  personnaliser

# Informations du site 
site_name: "Exercices sur les bases de donnÃ©es"
site_description: Exercices sur les bases de donnÃ©es
site_author: "Michael Meyroneinc-condy" 
copyright: 2022 sous licence <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr" target="_blank">CC BY-NC-SA 4.0</a> 
site_url: 

# Structure des dossiers :
docs_dir: docs

nav:
    - 'ğŸ¡ Accueil': 'index.md'
    - 'ğŸ”¨ CrÃ©ation et insertion':
        - 'LycÃ©e': '01_lycee/lycee.md'
        - 'SÃ©ries': '02_imdb/imdb.md'
    - 'ğŸ­ RequÃªtes simples':
        - 'PrÃ©noms': '31_prenoms/prenoms.md'
        - 'Ramens': '32_ramens/ramens.md'
    - 'ğŸˆ RequÃªtes sur plusieurs tables':
        - 'Films': '41_films/films.md'
        - 'Voitures': '42_cars/cars.md'
    - 'ğŸ¯ Exemples complets':
        - 'World': '51_world/world.md'
        - 'Netflix': '52_netflix/netflix.md'
    - 'ğŸ’¡ Memento SQL': 'memento_sql.md'
    - 'ğŸ‘ğŸ½ CrÃ©dits': 'credits.md'


# DÃ©finition du thÃ¨me https://squidfunk.github.io/mkdocs-material/creating-your-site/
theme:
    # custom_dir: my_theme_customizations/

    name: material
    font: false                     # RGPD ; pas de fonte Google
    language: fr                    # franÃ§ais
    favicon: favicon.png            # favicon perso
    logo: logo.png                  # logo perso
    palette:                        # Palettes de couleurs jour/nuit
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: light-blue
        accent: light-blue
        toggle:
            icon: material/weather-sunny
            name: Passer au mode nuit
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: blue
        accent: blue
        toggle:
            icon: material/weather-night
            name: Passer au mode jour
    features:
        - navigation.instant
        # - navigation.tabs
        - navigation.top
        - toc.integrate
        - header.autohide


markdown_extensions:
    - meta
    - abbr
    - def_list                      # Les listes de dÃ©finition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorÃ©s  !!! info "ma remarque"
    - pymdownx.details              #   qui peuvent se plier/dÃ©plier.
    - pymdownx.caret                # Passage ^^soulignÃ©^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surlignÃ©==.
    - pymdownx.tilde                # Passage ~~barrÃ©~~ ou en ~indice~.
    - pymdownx.highlight:           # Coloration syntaxique du code
        auto_title: true
        auto_title_map:
            "Python": "ğŸ Script Python"
            "Python Console Session": "ğŸ Console Python"
            "Text Only": "ğŸ“‹ Texte"
            "E-mail": "ğŸ“¥ EntrÃ©e"
            "Text Output": "ğŸ“¤ Sortie"
            "SQL": "ğŸ—‚ï¸ RequÃªte SQL"
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases Ã  cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed:              # Volets glissants.  === "Mon volet"
        alternate_style: true 
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:               # Ã‰mojis  :boom:
        emoji_index:     !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences:
    - pymdownx.arithmatex:
        generic: true
    - toc:
        permalink: âš“ï¸
        toc_depth: 1
    
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

plugins:

  - search # Inclure une barre de recherche
  - mkdocs-jupyter: # Convertir les fichiers .ipynb et .py en pages du site https://github.com/danielfrg/mkdocs-jupyter
      kernel_name: python3
      execute: False
      include_source: True
  - macros
  - sqlite-console
  - awesome-pages:
        collapse_single_pages: true


extra_javascript:
  - js/sortTable.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort/tablesort.min.js
  - js/tablesort/sorts/tablesort.date.min.js
  - js/tablesort/sorts/tablesort.dotsep.min.js
  - js/tablesort/sorts/tablesort.filesize.min.js
  - js/tablesort/sorts/tablesort.monthname.min.js
  - js/tablesort/sorts/tablesort.number.min.js

extra_css:
  - css/extra.css
